### ISSUE TITLE
ask for code

### ISSUE THREAD

**Issue by zuowanbushiwo** [donghoney0416/DeFTMamba#1]
May I ask if u can open source code? Used for reproduction and research. plz:)
So far, I haven’t seen any projects that combine speech separation and audio classification, and your article is really great.

Thanks！

**Comment by donghoney0416** [comment]
Thank you very much!
I submitted this manuscript to ICASSP 2025 and if I accept, I will consider to open source code.
Therefore, we appreciate your understanding that we are unable to release the code at this time.
